export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_IS_LOADING = 'SET_IS_LOADING';